name: 'Continuous Integration'

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths-ignore:
      - '.github/workflows/cd.yaml'
      - 'README.md'
      - 'LICENSE'

  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths-ignore:
      - '.github/workflows/cd.yaml'
      - 'README.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash

jobs:
  docker-build:
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm']

    runs-on: '${{ matrix.os }}'

    env:
      REGISTRY_URL: 'ghcr.io'
      IMAGE_NAME: 'deej'

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Extract Docker metadata'
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: '${{ env.REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}'

      - name: 'Build Docker images'
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: 'deployments/Dockerfile'
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          push: false
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'
